### your site title here

title: 排了一個好蛋
#site: https://doltegg.github.io
baseurl: /text # name of the repository
email: r90323011@ntu.edu.tw

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  
paginate: 6
paginate_path: "/page:num/"
### exclude the instructions / write-up in the README.md


# Tracker
#analytics: UA-83979019-4

# Comments
#disqus-shortname: webjeda-demo


#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: true #false
  profile: true #false
  startings: []
  

sass:
 style: compressed

exclude:
- README.md


gems: [jekyll-seo-tag, jekyll-paginate]


plugins:
  - jekyll-seo-tag
  - jekyll-paginate
